 La muestra está formada por 13 cegmentos. Aproximar una función 𝒚 que dependa de las variables.


In [1]:
# Definir los encabezados de la tabla
headers = ["Y", "X1", "X2", "X3", "X4"]

# Definir los datos de la tabla como una lista de listas
data = [
    [78.5, 7, 26, 6, 60],
    [74.3, 1, 29, 15, 52],
    [104.3, 11, 56, 8, 20],
    [87.6, 11, 31, 8, 47],
    [95.9, 7, 52, 6, 33],
    [109.2, 11, 55, 9, 22],
    [102.7, 3, 71, 17, 6],
    [72.5, 1, 31, 22, 44],
    [93.1, 2, 54, 18, 22],
    [115.9, 21, 47, 4, 26],
    [83.8, 1, 40, 23, 34],
    [113.3, 11, 66, 9, 12],
    [109.4, 10, 68, 8, 12]
]
from tabulate import tabulate

# Imprimir la tabla con encabezados
print(tabulate(data, headers=headers, tablefmt="grid"))
import pandas as pd
df = pd.DataFrame(data, columns=headers)
df


+-------+------+------+------+------+
|     Y |   X1 |   X2 |   X3 |   X4 |
+=======+======+======+======+======+
|  78.5 |    7 |   26 |    6 |   60 |
+-------+------+------+------+------+
|  74.3 |    1 |   29 |   15 |   52 |
+-------+------+------+------+------+
| 104.3 |   11 |   56 |    8 |   20 |
+-------+------+------+------+------+
|  87.6 |   11 |   31 |    8 |   47 |
+-------+------+------+------+------+
|  95.9 |    7 |   52 |    6 |   33 |
+-------+------+------+------+------+
| 109.2 |   11 |   55 |    9 |   22 |
+-------+------+------+------+------+
| 102.7 |    3 |   71 |   17 |    6 |
+-------+------+------+------+------+
|  72.5 |    1 |   31 |   22 |   44 |
+-------+------+------+------+------+
|  93.1 |    2 |   54 |   18 |   22 |
+-------+------+------+------+------+
| 115.9 |   21 |   47 |    4 |   26 |
+-------+------+------+------+------+
|  83.8 |    1 |   40 |   23 |   34 |
+-------+------+------+------+------+
| 113.3 |   11 |   66 |    9 |   12 |
+-------+---

Y  X1  X2  X3  X4
0    78.5   7  26   6  60
1    74.3   1  29  15  52
2   104.3  11  56   8  20
3    87.6  11  31   8  47
4    95.9   7  52   6  33
5   109.2  11  55   9  22
6   102.7   3  71  17   6
7    72.5   1  31  22  44
8    93.1   2  54  18  22
9   115.9  21  47   4  26
10   83.8   1  40  23  34
11  113.3  11  66   9  12
12  109.4  10  68   8  12

In [2]:
df2=df.copy()
df2["Y"]=df2["Y"]**0
df2

Y  X1  X2  X3  X4
0   1.0   7  26   6  60
1   1.0   1  29  15  52
2   1.0  11  56   8  20
3   1.0  11  31   8  47
4   1.0   7  52   6  33
5   1.0  11  55   9  22
6   1.0   3  71  17   6
7   1.0   1  31  22  44
8   1.0   2  54  18  22
9   1.0  21  47   4  26
10  1.0   1  40  23  34
11  1.0  11  66   9  12
12  1.0  10  68   8  12

In [3]:
df2["Y"] = 1
df2

Y  X1  X2  X3  X4
0   1   7  26   6  60
1   1   1  29  15  52
2   1  11  56   8  20
3   1  11  31   8  47
4   1   7  52   6  33
5   1  11  55   9  22
6   1   3  71  17   6
7   1   1  31  22  44
8   1   2  54  18  22
9   1  21  47   4  26
10  1   1  40  23  34
11  1  11  66   9  12
12  1  10  68   8  12

In [4]:
import numpy as np
import pandas as pd

# Crear la matriz X a partir de las variables independientes y agregar una columna de unos para el intercepto
X = df[['X1', 'X2', 'X3', 'X4']].values
X = np.insert(X, 0, 1, axis=1)

# Crear el vector Y a partir de la variable dependiente
Y = df['Y'].values.reshape(-1, 1) # Asegurarse de que Y sea un vector columna

print("Matriz X:")
print(X)
print("\nVector Y:")
print(Y)

Matriz X:
[[ 1  7 26  6 60]
 [ 1  1 29 15 52]
 [ 1 11 56  8 20]
 [ 1 11 31  8 47]
 [ 1  7 52  6 33]
 [ 1 11 55  9 22]
 [ 1  3 71 17  6]
 [ 1  1 31 22 44]
 [ 1  2 54 18 22]
 [ 1 21 47  4 26]
 [ 1  1 40 23 34]
 [ 1 11 66  9 12]
 [ 1 10 68  8 12]]

Vector Y:
[[ 78.5]
 [ 74.3]
 [104.3]
 [ 87.6]
 [ 95.9]
 [109.2]
 [102.7]
 [ 72.5]
 [ 93.1]
 [115.9]
 [ 83.8]
 [113.3]
 [109.4]]


In [5]:
import pandas as pd
data = {'Y': [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4],
        'X1': [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10],
        'X2': [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68],
        'X3': [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8],
        'X4': [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]}
df = pd.DataFrame(data)
# Conservar los valores originales de 'Y' para la regresión
# df["Y"]=1

In [6]:
# 2. Calcular la transpuesta de X (X')
X_t = X.T
print("--- Transpuesta de X (X') ---")
print(X_t)
print("\n" + "="*30 + "\n")

# 3. Multiplicar la transpuesta de X por X (X'X)
XtX = X_t @ X  # El operador @ significa multiplicación de matrices
print("--- Producto de X' por X (X'X) ---")
print(XtX)
print("\n" + "="*30 + "\n")


# 4. Calcular la inversa de (X'X)
XtX_inv = np.linalg.inv(XtX)
print("--- Inversa de (X'X) ---")
print(XtX_inv)
print("\n" + "="*30 + "\n")

# 5. Multiplicar la transpuesta de X por Y (X'Y)
XtY = X_t @ Y
print("--- Producto de X' por Y (X'Y) ---")
print(XtY)
print("\n" + "="*30 + "\n")

# 6. Finalmente, calcular los coeficientes Beta (β)
# β = (X'X)^-1 * (X'Y)
beta_coeficientes = XtX_inv @ XtY
print("--- Coeficientes de Regresión (β) ---")
print(beta_coeficientes)

# Mostrar los coeficientes de una forma más legible
print("\n--- Resultados Finales ---")
print(f"Intercepto (β₀): {beta_coeficientes[0][0]:.4f}")
print(f"Coeficiente X₁ (β₁): {beta_coeficientes[1][0]:.4f}")
print(f"Coeficiente X₂ (β₂): {beta_coeficientes[2][0]:.4f}")

--- Transpuesta de X (X') ---
[[ 1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 7  1 11 11  7 11  3  1  2 21  1 11 10]
 [26 29 56 31 52 55 71 31 54 47 40 66 68]
 [ 6 15  8  8  6  9 17 22 18  4 23  9  8]
 [60 52 20 47 33 22  6 44 22 26 34 12 12]]


--- Producto de X' por X (X'X) ---
[[   13    97   626   153   390]
 [   97  1139  4922   769  2620]
 [  626  4922 33050  7201 15739]
 [  153   769  7201  2293  4628]
 [  390  2620 15739  4628 15062]]


--- Inversa de (X'X) ---
[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]


--- Producto de X' por Y (X'Y) ---
[[ 1240.5]
 [10032. ]
 [62027.8]
 [13981.5]
 [34733.3]]


--- Coef

In [7]:
# formulas de error cuadratico


In [8]:
text = {'Y': [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4],
        'X1': [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10],
        'X2': [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68],
        'X3': [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8],
        'X4': [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]}
df = pd.DataFrame(text)
data_lines = []
print(df)

import numpy as np

# Calcular los valores predichos de Y (Y_hat) usando los coeficientes beta
Y_hat = X @ beta_coeficientes

#  hacer la resta de Y y Y_hat.
Y = Y.reshape(-1, 1)
Y_hat = Y_hat.reshape(-1, 1)

# Calcular el error y el error cuadrático
# Usamos los valores reales de Y directamente del vector Y y los predichos Y_hat
error = Y - Y_hat
error_squared = error ** 2

# df['Error'] = error
# df['Error^2'] = error_squared

print("Error (Y - Y_hat):")
print(error)
print("\nError cuadrático:")
print(error_squared)

        Y  X1  X2  X3  X4
0    78.5   7  26   6  60
1    74.3   1  29  15  52
2   104.3  11  56   8  20
3    87.6  11  31   8  47
4    95.9   7  52   6  33
5   109.2  11  55   9  22
6   102.7   3  71  17   6
7    72.5   1  31  22  44
8    93.1   2  54  18  22
9   115.9  21  47   4  26
10   83.8   1  40  23  34
11  113.3  11  66   9  12
12  109.4  10  68   8  12
Error (Y - Y_hat):
[[ 0.00476042]
 [ 1.5112007 ]
 [-1.67093753]
 [-1.72710025]
 [ 0.25075556]
 [ 3.9254427 ]
 [-1.44866909]
 [-3.17498852]
 [ 1.37834948]
 [ 0.281548  ]
 [ 1.99098357]
 [ 0.97298904]
 [-2.29433407]]

Error cuadrático:
[[2.26615859e-05]
 [2.28372756e+00]
 [2.79203224e+00]
 [2.98287529e+00]
 [6.28783518e-02]
 [1.54091004e+01]
 [2.09864212e+00]
 [1.00805521e+01]
 [1.89984728e+00]
 [7.92692757e-02]
 [3.96401558e+00]
 [9.46707662e-01]
 [5.26396884e+00]]


In [9]:
# error cuadratico medio
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd

# Re-create the dataframe df
data = {'Y': [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4],
        'X1': [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10],
        'X2': [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68],
        'X3': [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8],
        'X4': [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]}
df = pd.DataFrame(data)

# Crear la matriz X a partir de las variables independientes y agregar una columna de unos para el intercepto
X = df[['X1', 'X2', 'X3', 'X4']].values
X = np.insert(X, 0, 1, axis=1)

# Crear el vector Y a partir de la variable dependiente
Y = df['Y'].values.reshape(-1, 1) # Asegurarse de que Y sea un vector columna

# 2. Calcular la transpuesta de X (X')
X_t = X.T

# 3. Multiplicar la transpuesta de X por X (X'X)
XtX = X_t @ X  # El operador @ significa multiplicación de matrices

# 4. Calcular la inversa de (X'X)
XtX_inv = np.linalg.inv(XtX)

# 5. Multiplicar la transpuesta de X por Y (X'Y)
XtY = X_t @ Y

# 6. Finalmente, calcular los coeficientes Beta (β)
# β = (X'X)^-1 * (X'Y)
beta_coeficientes = XtX_inv @ XtY

# Re-create X and Y from the dataframe and calculate Y_hat
X = df[['X1', 'X2', 'X3', 'X4']].values
X = np.insert(X, 0, 1, axis=1)
Y = df['Y'].values.reshape(-1, 1)
Y_hat = X @ beta_coeficientes

mse = mean_squared_error(Y, Y_hat)
print("Mean Squared Error (MSE):", mse)

## error cuadratico medio raiz
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error (RMSE): {rmse}")

### error adsoluto medio
mae = mean_absolute_error(Y, Y_hat)
print(f"Mean Absolute Error (MAE) es: {mae}")

# Calcular error porcentual absoluto medio (MAPE)
# Calculate error MAPE
error = Y - Y_hat
mape = (np.abs(error) / np.abs(Y)).mean() * 100
print(f"Mean Absolute Percentage Error (MAPE): {mape}")

## error cuadratico
media_y = df['Y'].mean()
print(f"La media de y es: {media_y}")

Mean Squared Error (MSE): 3.6818184115768533
Root Mean Squared Error (RMSE): 1.918806507070698
Mean Absolute Error (MAE) es: 1.5870814560772506
Mean Absolute Percentage Error (MAPE): 1.7165354713049048
La media de y es: 95.42307692307692


In [10]:
#metodo Moore-Penrose.
import pandas as pd
data = {'Y': [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4],
        'X1': [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10],
        'X2': [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68],
        'X3': [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8],
        'X4': [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]}
# Asignar los datos a las variables x e y
x = pd.DataFrame(data, columns=['X1', 'X2', 'X3', 'X4'])
y = pd.Series(data['Y'])
df = pd.DataFrame(data)
df


Y  X1  X2  X3  X4
0    78.5   7  26   6  60
1    74.3   1  29  15  52
2   104.3  11  56   8  20
3    87.6  11  31   8  47
4    95.9   7  52   6  33
5   109.2  11  55   9  22
6   102.7   3  71  17   6
7    72.5   1  31  22  44
8    93.1   2  54  18  22
9   115.9  21  47   4  26
10   83.8   1  40  23  34
11  113.3  11  66   9  12
12  109.4  10  68   8  12

In [11]:
df2=df.copy()
df2["y"]=np.ones(len(df))
df2

Y  X1  X2  X3  X4    y
0    78.5   7  26   6  60  1.0
1    74.3   1  29  15  52  1.0
2   104.3  11  56   8  20  1.0
3    87.6  11  31   8  47  1.0
4    95.9   7  52   6  33  1.0
5   109.2  11  55   9  22  1.0
6   102.7   3  71  17   6  1.0
7    72.5   1  31  22  44  1.0
8    93.1   2  54  18  22  1.0
9   115.9  21  47   4  26  1.0
10   83.8   1  40  23  34  1.0
11  113.3  11  66   9  12  1.0
12  109.4  10  68   8  12  1.0

In [12]:
X=np.array(df2)
X.shape

(13, 6)

In [13]:
Xpinv= np.linalg.pinv(X)
Xpinv.shape

(6, 13)

In [14]:
y = np.array(df[["Y"]])
y.shape

(13, 1)

In [15]:
betas = Xpinv @ y
print(betas.shape)
betas

(6, 1)


array([[ 1.00000000e+00],
       [-9.03024600e-15],
       [-7.22294054e-15],
       [-5.78068274e-15],
       [-1.21474243e-14],
       [ 4.64599338e-13]])